#!/usr/bin/env python3
"""Build api-knowledge-store.json: one array of API objects with full metadata per API."""

import json
from datetime import date

def base_url(path):
    return {
        "sandbox": f"https://api-sandbox.company.com{path}",
        "staging": f"https://api-staging.company.com{path}",
        "production": f"https://api.company.com{path}",
    }

def api(id, name, domain, description, team, developers, service, auth, tags, path_prefix,
        endpoints, conf_space, conf_page, conf_title, bb_repo, bb_path, hash_suffix,
        use_cases, consumers, pii=None, deps=None, link_extra=None):
    path = path_prefix
    envs = base_url(path_prefix)
    deps = deps or []
    pii = pii or []
    reg = ["telecom-reg"] if pii else []
    link_extra = link_extra or []
    return {
        "id": id,
        "name": name,
        "domain": domain,
        "description": description,
        "team": team,
        "developers": developers,
        "service": service,
        "auth": auth,
        "lifecycle": "GA",
        "tags": tags,
        "environments": envs,
        "api_versions": [{
            "semver": "1.0.0",
            "status": "current",
            "released_at": "2024-09-01",
            "code_version_ref": f"main@{service['logical_unit']}",
            "doc_version_ref": f"Confluence {name} v1",
        }],
        "endpoints": endpoints,
        "sources_confluence": {
            "space_key": conf_space,
            "page_id": "1" * 9,
            "page_title": conf_title,
            "labels": ["api-docs", domain],
            "version": 1,
            "url": f"https://confluence.company.com/display/{conf_space}/{conf_title.replace(' ', '+')}",
        },
        "sources_bitbucket": {
            "repo": bb_repo,
            "branch": "main",
            "openapi_path": bb_path,
            "last_commit": "a1b2c3d4",
            "url": f"https://bitbucket.company.com/projects/{bb_repo.split('/')[0].upper()}/repos/{bb_repo.split('/')[-1]}",
        },
        "openapi_spec": {"content_hash": f"sha256:{hash_suffix}", "format": "yaml", "last_synced": str(date.today())},
        "metrics": {"request_count": 50000, "p95_latency_ms": 60, "error_rate": 0.003, "rank_by_usage": 5},
        "dependencies": deps,
        "compliance": {
            "pii_classification": pii,
            "data_retention_days": 365 if pii else 90,
            "audit_logged": True,
            "approval_workflow": "security-review" if pii else "standard",
            "last_audit": "2025-01-15",
            "regulatory_tags": reg,
        },
        "links": [
            {"type": "confluence", "url": f"https://confluence.company.com/display/{conf_space}/{conf_title.replace(' ', '+')}", "label": "Documentation"},
            {"type": "bitbucket", "url": f"https://bitbucket.company.com/repos/{bb_repo}", "label": "Source"},
        ] + link_extra,
        "description_extended": {"summary": description, "use_cases": use_cases, "target_consumers": consumers},
    }

# Reusable team/dev/service snippets
T_RETAIL = {"name": "Retail & Store APIs", "org_unit": "Consumer Business / Digital", "squad": "Store & Location Services", "slack_channel": "#retail-apis", "jira_project": "RETAIL"}
T_PAY = {"name": "Payments & Banking", "org_unit": "Finance & Operations", "squad": "Payment APIs", "slack_channel": "#payments-api", "jira_project": "PAY"}
T_IDENTITY = {"name": "Identity & SIM", "org_unit": "Network & Identity", "squad": "SIM & KYC", "slack_channel": "#identity-apis", "jira_project": "ID"}
T_CUSTOMER = {"name": "Customer 360", "org_unit": "Consumer Business", "squad": "Customer Data APIs", "slack_channel": "#customer-apis", "jira_project": "CUST"}
T_BILLING = {"name": "Billing & Usage", "org_unit": "Consumer Business", "squad": "Billing APIs", "slack_channel": "#billing-apis", "jira_project": "BILL"}
T_NETWORK = {"name": "Network & Coverage", "org_unit": "Network", "squad": "Network APIs", "slack_channel": "#network-apis", "jira_project": "NET"}
T_CARE = {"name": "Care & Support", "org_unit": "Customer Experience", "squad": "Care APIs", "slack_channel": "#care-apis", "jira_project": "CARE"}
T_PARTNER = {"name": "Partner & Channel", "org_unit": "Sales", "squad": "Partner APIs", "slack_channel": "#partner-apis", "jira_project": "PART"}
DEV = [{"name": "Jane Doe", "email": "jane.doe@company.com", "role": "Tech Lead"}, {"name": "John Smith", "email": "john.smith@company.com", "role": "Backend"}]
DEV2 = [{"name": "Alice Chen", "email": "alice.chen@company.com", "role": "API Owner"}, {"name": "Bob Wilson", "email": "bob.wilson@company.com", "role": "Backend"}]
DEV3 = [{"name": "Carol Brown", "email": "carol.brown@company.com", "role": "Tech Lead"}]

def main():
    apis = [
        api(
            "api-store-location", "Store Location API", "retail",
            "Get store/outlet locations, opening hours, and availability by geography or filters.",
            T_RETAIL, DEV,
            {"name": "Store Locator Service", "logical_unit": "retail-store-locator", "description": "Store/outlet location and availability"},
            ["API_KEY", "OAuth2"], ["retail", "location", "stores", "outlets"], "/retail/store-location",
            [{"method": "GET", "path": "/v1/stores", "summary": "Search stores by location or filters", "operation_id": "searchStores"}, {"method": "GET", "path": "/v1/stores/{storeId}", "summary": "Get store details by ID", "operation_id": "getStoreById"}],
            "RETail", "123456789", "Store Location API", "retail/store-locator-svc", "src/main/resources/openapi/store-location-api.yaml", "9a8b7c6d5e4f",
            ["Store finder", "Agent locator", "Inventory availability"], ["Web app", "Mobile app", "Partner portals"],
            link_extra=[{"type": "developer_portal", "url": "https://developer.company.com/apis/store-location", "label": "Developer Portal"}],
        ),
        api(
            "api-bank-check-balance", "Bank Check Balance API", "payments",
            "Verify bank account and check balance for payment flows (top-up, bill pay).",
            T_PAY, DEV2,
            {"name": "Bank Check Service", "logical_unit": "payments-bank-check", "description": "Balance check and bank verification"},
            ["OAuth2", "mTLS"], ["payments", "banking", "balance", "verification", "PII"], "/payments/bank-check",
            [{"method": "POST", "path": "/v1/accounts/verify", "summary": "Verify bank account and return balance", "operation_id": "verifyAccount"}],
            "PAY", "234567890", "Bank Check Balance API", "payments/bank-check-svc", "api/openapi.yaml", "1a2b3c4d5e6f",
            ["Account verification", "Balance check before payment", "Reconciliation"], ["Payments service", "Billing", "Partner gateways"],
            pii=["financial_account", "balance"], deps=[], link_extra=[{"type": "runbook", "url": "https://runbook.company.com/payments/bank-check", "label": "Runbook"}],
        ),
        api(
            "api-sim-swaps", "SIM Swap API", "identity",
            "Initiate and query SIM swap requests; check swap eligibility and status.",
            T_IDENTITY, DEV3 + [DEV[1]],
            {"name": "SIM Management Service", "logical_unit": "identity-sim", "description": "SIM swap, SIM status, device binding"},
            ["OAuth2", "API_KEY"], ["identity", "SIM", "swap", "fraud", "PII"], "/identity/sim-swap",
            [{"method": "POST", "path": "/v1/sim/swap", "summary": "Submit SIM swap request", "operation_id": "requestSimSwap"}, {"method": "GET", "path": "/v1/sim/swap/{requestId}", "summary": "Get SIM swap status", "operation_id": "getSimSwapStatus"}],
            "ID", "345678901", "SIM Swap API", "identity/sim-management-svc", "specs/openapi/sim-swap-api.yaml", "2b3c4d5e6f7a",
            ["SIM replacement", "Device change", "Fraud detection"], ["Care apps", "Retail POS", "Fraud systems"],
            pii=["subscriber_id", "device_id"], deps=[{"api_name": "Customer Status API", "relationship": "calls", "context": "Customer verification for SIM swap"}],
            link_extra=[{"type": "postman", "url": "https://api.company.com/postman/identity/sim-swap", "label": "Postman Collection"}],
        ),
        api(
            "api-customer-status", "Customer Status API", "customer",
            "Customer profile summary, account status, segment, and service eligibility.",
            T_CUSTOMER, [DEV[0], DEV3[0]],
            {"name": "Customer 360 Service", "logical_unit": "customer-profile", "description": "Unified customer profile and status"},
            ["OAuth2"], ["customer", "profile", "status", "eligibility", "PII"], "/customer/status",
            [{"method": "GET", "path": "/v2/customers/{customerId}/status", "summary": "Get customer account status and segment", "operation_id": "getCustomerStatus"}],
            "CUST", "456789012", "Customer Status API", "customer/customer-360-svc", "openapi/customer-status-v2.yaml", "3c4d5e6f7a8b",
            ["Personalization", "Eligibility checks", "Dashboard", "Care"], ["All consumer-facing apps", "CRM", "Billing"],
            pii=["customer_id", "contact", "segment"],
        ),
        api(
            "api-topup", "Top-Up / Recharge API", "payments",
            "Prepaid airtime and data top-up, bundle purchase, and recharge history.",
            T_PAY, DEV2,
            {"name": "Top-Up & Recharge Service", "logical_unit": "payments-topup", "description": "Prepaid top-up and recharge"},
            ["OAuth2", "API_KEY"], ["payments", "topup", "recharge", "prepaid", "airtime"], "/payments/topup",
            [{"method": "POST", "path": "/v1/topup", "summary": "Execute top-up for a subscriber", "operation_id": "executeTopup"}, {"method": "GET", "path": "/v1/topup/history", "summary": "Get recharge history", "operation_id": "getTopupHistory"}],
            "PAY", "567890123", "Top-Up API", "payments/topup-svc", "api/spec.yaml", "4d5e6f7a8b9c",
            ["Self-care top-up", "Agent recharge", "Bundle purchase"], ["Mobile app", "USSD", "Retail POS", "Partners"],
            deps=[{"api_name": "Bank Check Balance API", "relationship": "calls", "context": "Balance check before top-up"}, {"api_name": "Customer Status API", "relationship": "calls", "context": "Eligibility before recharge"}],
        ),
        api(
            "api-bill-pay", "Bill Pay API", "payments",
            "Pay postpaid bills, schedule payments, and retrieve payment status.",
            T_PAY, DEV2,
            {"name": "Bill Pay Service", "logical_unit": "payments-billpay", "description": "Postpaid bill payment"},
            ["OAuth2", "API_KEY"], ["payments", "billing", "bill-pay", "postpaid"], "/payments/bill-pay",
            [{"method": "POST", "path": "/v1/bills/pay", "summary": "Pay a bill", "operation_id": "payBill"}, {"method": "GET", "path": "/v1/bills/{billId}/payment-status", "summary": "Get payment status", "operation_id": "getPaymentStatus"}],
            "PAY", "678901234", "Bill Pay API", "payments/bill-pay-svc", "openapi.yaml", "5e6f7a8b9c0d",
            ["Bill payment", "Scheduled payment", "Payment status"], ["Mobile app", "Web", "IVR", "Agents"],
            pii=["payment_instrument"],
        ),
        api(
            "api-usage-consumption", "Usage / Consumption API", "billing",
            "Data, voice, and SMS usage and consumption for prepaid and postpaid.",
            T_BILLING, DEV,
            {"name": "Usage Service", "logical_unit": "billing-usage", "description": "Usage and consumption aggregation"},
            ["OAuth2"], ["billing", "usage", "consumption", "data", "voice"], "/billing/usage",
            [{"method": "GET", "path": "/v1/subscribers/{msisdn}/usage", "summary": "Get current period usage", "operation_id": "getUsage"}, {"method": "GET", "path": "/v1/subscribers/{msisdn}/usage/history", "summary": "Get usage history", "operation_id": "getUsageHistory"}],
            "BILL", "789012345", "Usage API", "billing/usage-svc", "spec/usage-api.yaml", "6f7a8b9c0d1e",
            ["Usage dashboard", "Alerts", "Fair usage"], ["Self-care", "Care", "Analytics"],
            pii=["msisdn", "usage_data"],
        ),
        api(
            "api-device-swap", "Device Swap API", "identity",
            "Register device change and swap device binding for a subscriber.",
            T_IDENTITY, DEV3,
            {"name": "Device Management Service", "logical_unit": "identity-device", "description": "Device binding and swap"},
            ["OAuth2", "API_KEY"], ["identity", "device", "swap", "IMEI"], "/identity/device-swap",
            [{"method": "POST", "path": "/v1/device/swap", "summary": "Submit device swap request", "operation_id": "requestDeviceSwap"}, {"method": "GET", "path": "/v1/device/swap/{requestId}", "summary": "Get device swap status", "operation_id": "getDeviceSwapStatus"}],
            "ID", "890123456", "Device Swap API", "identity/device-svc", "api/openapi.yaml", "7a8b9c0d1e2f",
            ["Device change", "IMEI update", "Lost device"], ["Care", "Retail", "Fraud"],
            pii=["subscriber_id", "device_id", "IMEI"],
        ),
        api(
            "api-mnp", "Number Portability (MNP) API", "identity",
            "Check portability status and initiate number port-in/port-out requests.",
            T_IDENTITY, DEV3,
            {"name": "MNP Service", "logical_unit": "identity-mnp", "description": "Mobile number portability"},
            ["OAuth2", "mTLS"], ["identity", "MNP", "portability", "port-in", "port-out"], "/identity/mnp",
            [{"method": "GET", "path": "/v1/mnp/check/{number}", "summary": "Check portability eligibility", "operation_id": "checkPortability"}, {"method": "POST", "path": "/v1/mnp/request", "summary": "Submit port request", "operation_id": "submitPortRequest"}],
            "ID", "901234567", "MNP API", "identity/mnp-svc", "specs/openapi.yaml", "8b9c0d1e2f3a",
            ["Port-in", "Port-out", "Eligibility check"], ["Care", "Retail", "Regulatory"],
            pii=["msisdn", "subscriber_id"],
        ),
        api(
            "api-otp-verification", "OTP / Verification API", "identity",
            "Send and verify OTP for login, transactions, and step-up authentication.",
            T_IDENTITY, DEV2,
            {"name": "Verification Service", "logical_unit": "identity-otp", "description": "OTP generation and verification"},
            ["API_KEY", "OAuth2"], ["identity", "OTP", "verification", "2FA", "security"], "/identity/otp",
            [{"method": "POST", "path": "/v1/otp/send", "summary": "Send OTP", "operation_id": "sendOtp"}, {"method": "POST", "path": "/v1/otp/verify", "summary": "Verify OTP", "operation_id": "verifyOtp"}],
            "ID", "012345678", "OTP API", "identity/otp-svc", "openapi/otp-api.yaml", "9c0d1e2f3a4b",
            ["Login", "Transaction confirmation", "Step-up auth"], ["All apps", "Partners"],
            pii=["phone_number", "session_id"],
        ),
        api(
            "api-subscriber-registration", "Subscriber Registration API", "customer",
            "Register new prepaid/postpaid subscribers and validate identity.",
            T_CUSTOMER, DEV + [DEV2[0]],
            {"name": "Registration Service", "logical_unit": "customer-registration", "description": "Subscriber onboarding"},
            ["OAuth2", "mTLS"], ["customer", "registration", "onboarding", "KYC"], "/customer/registration",
            [{"method": "POST", "path": "/v1/subscribers/register", "summary": "Register new subscriber", "operation_id": "registerSubscriber"}, {"method": "GET", "path": "/v1/subscribers/register/{requestId}/status", "summary": "Get registration status", "operation_id": "getRegistrationStatus"}],
            "CUST", "112345678", "Subscriber Registration API", "customer/registration-svc", "api/spec.yaml", "0d1e2f3a4b5c",
            ["New activation", "Channel onboarding", "KYC"], ["Retail", "Care", "Partners"],
            pii=["name", "id_number", "address", "msisdn"],
        ),
        api(
            "api-balance-inquiry", "Balance Inquiry API", "billing",
            "Prepaid balance and postpaid account balance and credit limit.",
            T_BILLING, DEV,
            {"name": "Balance Service", "logical_unit": "billing-balance", "description": "Balance and credit inquiry"},
            ["OAuth2"], ["billing", "balance", "prepaid", "postpaid"], "/billing/balance",
            [{"method": "GET", "path": "/v1/subscribers/{msisdn}/balance", "summary": "Get current balance", "operation_id": "getBalance"}],
            "BILL", "212345678", "Balance Inquiry API", "billing/balance-svc", "openapi.yaml", "1e2f3a4b5c6d",
            ["Balance check", "USSD", "Dashboard"], ["Self-care", "USSD", "Agents"],
            pii=["msisdn"],
        ),
        api(
            "api-bundle-purchase", "Bundle Purchase API", "billing",
            "Purchase data, voice, and SMS bundles; list available bundles and active bundles.",
            T_BILLING, DEV,
            {"name": "Bundle Service", "logical_unit": "billing-bundles", "description": "Bundle catalog and purchase"},
            ["OAuth2", "API_KEY"], ["billing", "bundles", "data", "voice", "SMS"], "/billing/bundles",
            [{"method": "GET", "path": "/v1/bundles", "summary": "List available bundles", "operation_id": "listBundles"}, {"method": "POST", "path": "/v1/bundles/purchase", "summary": "Purchase a bundle", "operation_id": "purchaseBundle"}],
            "BILL", "312345678", "Bundle Purchase API", "billing/bundle-svc", "spec/bundles-api.yaml", "2f3a4b5c6d7e",
            ["Data bundles", "Voice/SMS packs", "Promo bundles"], ["Mobile app", "USSD", "Retail"],
            deps=[{"api_name": "Top-Up API", "relationship": "calls", "context": "Debit for bundle purchase"}],
        ),
        api(
            "api-roaming-status", "Roaming Status API", "network",
            "Check roaming status, activate roaming packs, and get roaming usage.",
            T_NETWORK, DEV3,
            {"name": "Roaming Service", "logical_unit": "network-roaming", "description": "Roaming status and packs"},
            ["OAuth2"], ["network", "roaming", "international"], "/network/roaming",
            [{"method": "GET", "path": "/v1/roaming/status/{msisdn}", "summary": "Get roaming status", "operation_id": "getRoamingStatus"}, {"method": "POST", "path": "/v1/roaming/packs/activate", "summary": "Activate roaming pack", "operation_id": "activateRoamingPack"}],
            "NET", "412345678", "Roaming API", "network/roaming-svc", "api/openapi.yaml", "3a4b5c6d7e8f",
            ["Roaming activation", "Travel packs", "Usage abroad"], ["Self-care", "Care"],
            pii=["msisdn"],
        ),
        api(
            "api-coverage-check", "Coverage Check API", "network",
            "Check network coverage and quality by location (lat/long or address).",
            T_NETWORK, DEV3,
            {"name": "Coverage Service", "logical_unit": "network-coverage", "description": "Coverage and signal strength"},
            ["API_KEY", "OAuth2"], ["network", "coverage", "signal", "location"], "/network/coverage",
            [{"method": "GET", "path": "/v1/coverage", "summary": "Get coverage by coordinates", "operation_id": "getCoverageByLocation"}, {"method": "GET", "path": "/v1/coverage/address", "summary": "Get coverage by address", "operation_id": "getCoverageByAddress"}],
            "NET", "512345678", "Coverage API", "network/coverage-svc", "specs/coverage-api.yaml", "4b5c6d7e8f9a",
            ["Coverage map", "Store locator", "Troubleshooting"], ["Web", "Mobile", "Care"],
        ),
        api(
            "api-complaints-tickets", "Complaints / Tickets API", "care",
            "Create and track customer complaints and support tickets.",
            T_CARE, DEV2,
            {"name": "Care Ticket Service", "logical_unit": "care-tickets", "description": "Complaint and ticket management"},
            ["OAuth2"], ["care", "complaints", "tickets", "support"], "/care/tickets",
            [{"method": "POST", "path": "/v1/tickets", "summary": "Create ticket", "operation_id": "createTicket"}, {"method": "GET", "path": "/v1/tickets/{ticketId}", "summary": "Get ticket status", "operation_id": "getTicket"}],
            "CARE", "612345678", "Complaints API", "care/ticket-svc", "openapi/tickets.yaml", "5c6d7e8f9a0b",
            ["Complaint registration", "Ticket tracking", "Escalation"], ["Care", "CRM", "Self-care"],
            pii=["customer_id", "contact", "complaint_text"],
        ),
        api(
            "api-payment-history", "Payment History API", "payments",
            "Retrieve payment and transaction history for a subscriber or account.",
            T_PAY, DEV2,
            {"name": "Payment History Service", "logical_unit": "payments-history", "description": "Payment and transaction history"},
            ["OAuth2"], ["payments", "history", "transactions"], "/payments/history",
            [{"method": "GET", "path": "/v1/payments/history", "summary": "Get payment history", "operation_id": "getPaymentHistory"}],
            "PAY", "712345678", "Payment History API", "payments/history-svc", "api/spec.yaml", "6d7e8f9a0b1c",
            ["Transaction history", "Reconciliation", "Statements"], ["Self-care", "Billing", "Finance"],
            pii=["customer_id", "payment_instrument"],
        ),
        api(
            "api-invoice-download", "Invoice Download API", "billing",
            "Generate and download postpaid invoices (PDF) and list invoice summaries.",
            T_BILLING, DEV,
            {"name": "Invoice Service", "logical_unit": "billing-invoice", "description": "Invoice generation and download"},
            ["OAuth2"], ["billing", "invoice", "postpaid", "PDF"], "/billing/invoices",
            [{"method": "GET", "path": "/v1/invoices", "summary": "List invoices", "operation_id": "listInvoices"}, {"method": "GET", "path": "/v1/invoices/{invoiceId}/download", "summary": "Download invoice PDF", "operation_id": "downloadInvoice"}],
            "BILL", "812345678", "Invoice API", "billing/invoice-svc", "openapi.yaml", "7e8f9a0b1c2d",
            ["Invoice download", "Billing history", "Compliance"], ["Self-care", "Enterprise", "Finance"],
            pii=["customer_id", "billing_address"],
        ),
        api(
            "api-plan-change", "Plan Change / Migration API", "billing",
            "Change tariff plan, migrate prepaid to postpaid, and check eligibility.",
            T_BILLING, DEV,
            {"name": "Plan Management Service", "logical_unit": "billing-plans", "description": "Plan change and migration"},
            ["OAuth2"], ["billing", "plans", "migration", "tariff"], "/billing/plans",
            [{"method": "GET", "path": "/v1/plans/eligible", "summary": "Get eligible plans", "operation_id": "getEligiblePlans"}, {"method": "POST", "path": "/v1/plans/change", "summary": "Request plan change", "operation_id": "changePlan"}],
            "BILL", "912345678", "Plan Change API", "billing/plan-svc", "spec/plans-api.yaml", "8f9a0b1c2d3e",
            ["Plan upgrade/downgrade", "Prepaid to postpaid", "Eligibility"], ["Care", "Retail", "Self-care"],
            pii=["msisdn", "customer_id"],
        ),
        api(
            "api-loyalty-rewards", "Loyalty / Rewards API", "customer",
            "Loyalty points balance, earn/burn, and rewards catalog and redemption.",
            T_CUSTOMER, DEV2,
            {"name": "Loyalty Service", "logical_unit": "customer-loyalty", "description": "Loyalty and rewards"},
            ["OAuth2"], ["customer", "loyalty", "rewards", "points"], "/customer/loyalty",
            [{"method": "GET", "path": "/v1/loyalty/points", "summary": "Get points balance", "operation_id": "getPoints"}, {"method": "POST", "path": "/v1/loyalty/redeem", "summary": "Redeem rewards", "operation_id": "redeemRewards"}],
            "CUST", "022345678", "Loyalty API", "customer/loyalty-svc", "api/openapi.yaml", "9a0b1c2d3e4f",
            ["Points balance", "Redemption", "Promos"], ["Mobile app", "Web", "Retail"],
            pii=["customer_id"],
        ),
        api(
            "api-agent-commission", "Agent Commission API", "partner",
            "Agent commission balance, transactions, and payout history.",
            T_PARTNER, DEV3,
            {"name": "Commission Service", "logical_unit": "partner-commission", "description": "Agent commission and payout"},
            ["OAuth2", "API_KEY"], ["partner", "agent", "commission", "payout"], "/partner/commission",
            [{"method": "GET", "path": "/v1/agents/{agentId}/commission/balance", "summary": "Get commission balance", "operation_id": "getCommissionBalance"}, {"method": "GET", "path": "/v1/agents/{agentId}/commission/history", "summary": "Get commission history", "operation_id": "getCommissionHistory"}],
            "PART", "122345678", "Agent Commission API", "partner/commission-svc", "specs/commission-api.yaml", "0b1c2d3e4f5a",
            ["Agent dashboard", "Payout", "Reconciliation"], ["Agent portal", "Finance"],
            pii=["agent_id", "bank_account"],
        ),
        api(
            "api-kyc-verification", "KYC / Identity Verification API", "identity",
            "Submit and verify KYC documents and identity for regulatory compliance.",
            T_IDENTITY, DEV3,
            {"name": "KYC Service", "logical_unit": "identity-kyc", "description": "KYC and identity verification"},
            ["OAuth2", "mTLS"], ["identity", "KYC", "verification", "compliance", "PII"], "/identity/kyc",
            [{"method": "POST", "path": "/v1/kyc/submit", "summary": "Submit KYC documents", "operation_id": "submitKyc"}, {"method": "GET", "path": "/v1/kyc/status/{customerId}", "summary": "Get KYC status", "operation_id": "getKycStatus"}],
            "ID", "222345678", "KYC API", "identity/kyc-svc", "openapi/kyc.yaml", "1c2d3e4f5a6b",
            ["Onboarding", "Re-KYC", "Compliance"], ["Registration", "Care", "Partners"],
            pii=["id_document", "photo", "address"],
        ),
        api(
            "api-blacklist-fraud", "Blacklist / Fraud API", "identity",
            "Check and manage blacklist; report and query fraud indicators.",
            T_IDENTITY, DEV3,
            {"name": "Fraud Service", "logical_unit": "identity-fraud", "description": "Blacklist and fraud management"},
            ["OAuth2", "mTLS"], ["identity", "fraud", "blacklist", "security"], "/identity/fraud",
            [{"method": "GET", "path": "/v1/blacklist/check/{msisdn}", "summary": "Check blacklist", "operation_id": "checkBlacklist"}, {"method": "POST", "path": "/v1/fraud/report", "summary": "Report fraud incident", "operation_id": "reportFraud"}],
            "ID", "322345678", "Blacklist Fraud API", "identity/fraud-svc", "api/spec.yaml", "2d3e4f5a6b7c",
            ["Fraud check", "Blacklist", "Reporting"], ["Activation", "Care", "Fraud team"],
            pii=["msisdn", "incident_details"],
        ),
        api(
            "api-notification-preferences", "Notification Preferences API", "customer",
            "Get and update notification preferences (SMS, email, push) per channel.",
            T_CUSTOMER, DEV2,
            {"name": "Preferences Service", "logical_unit": "customer-preferences", "description": "Notification and contact preferences"},
            ["OAuth2"], ["customer", "notifications", "preferences", "consent"], "/customer/notifications/preferences",
            [{"method": "GET", "path": "/v1/preferences/notifications", "summary": "Get notification preferences", "operation_id": "getPreferences"}, {"method": "PUT", "path": "/v1/preferences/notifications", "summary": "Update preferences", "operation_id": "updatePreferences"}],
            "CUST", "422345678", "Notification Preferences API", "customer/preferences-svc", "openapi/preferences.yaml", "3e4f5a6b7c8d",
            ["Opt-in/opt-out", "Channel preferences", "GDPR"], ["Self-care", "Campaign", "Care"],
            pii=["customer_id", "contact_preferences"],
        ),
        api(
            "api-product-catalog", "Product Catalog API", "retail",
            "Product and offer catalog for devices, plans, and add-ons.",
            T_RETAIL, DEV,
            {"name": "Catalog Service", "logical_unit": "retail-catalog", "description": "Product and offer catalog"},
            ["API_KEY", "OAuth2"], ["retail", "catalog", "products", "offers"], "/retail/catalog",
            [{"method": "GET", "path": "/v1/products", "summary": "List products", "operation_id": "listProducts"}, {"method": "GET", "path": "/v1/products/{productId}", "summary": "Get product details", "operation_id": "getProduct"}],
            "RETail", "522345678", "Product Catalog API", "retail/catalog-svc", "spec/catalog-api.yaml", "4f5a6b7c8d9e",
            ["Product browse", "Pricing", "Availability"], ["Web", "Mobile", "Retail POS"],
        ),
        api(
            "api-order-status", "Order Status API", "retail",
            "Track order status for devices, SIMs, and home delivery.",
            T_RETAIL, DEV,
            {"name": "Order Service", "logical_unit": "retail-orders", "description": "Order tracking and status"},
            ["OAuth2"], ["retail", "orders", "tracking", "fulfillment"], "/retail/orders",
            [{"method": "GET", "path": "/v1/orders/{orderId}", "summary": "Get order status", "operation_id": "getOrderStatus"}, {"method": "GET", "path": "/v1/orders", "summary": "List orders for customer", "operation_id": "listOrders"}],
            "RETail", "622345678", "Order Status API", "retail/order-svc", "api/orders-openapi.yaml", "5a6b7c8d9e0f",
            ["Order tracking", "Delivery status", "Returns"], ["Self-care", "Retail", "Care"],
            pii=["customer_id", "delivery_address"],
        ),
        api(
            "api-activation-provisioning", "Activation / Provisioning API", "identity",
            "Activate new lines, provision services, and sync with network.",
            T_IDENTITY, DEV3,
            {"name": "Provisioning Service", "logical_unit": "identity-provisioning", "description": "Activation and service provisioning"},
            ["OAuth2", "mTLS"], ["identity", "activation", "provisioning", "network"], "/identity/activation",
            [{"method": "POST", "path": "/v1/activation", "summary": "Activate line", "operation_id": "activateLine"}, {"method": "GET", "path": "/v1/activation/{requestId}/status", "summary": "Get activation status", "operation_id": "getActivationStatus"}],
            "ID", "722345678", "Activation API", "identity/provisioning-svc", "specs/activation-api.yaml", "6b7c8d9e0f1a",
            ["New activation", "Service provisioning", "Network sync"], ["Retail", "Care", "Partners"],
            pii=["msisdn", "sim_iccid", "device_imei"],
        ),
        api(
            "api-partner-onboarding", "Partner Onboarding API", "partner",
            "Onboard partners, manage credentials, and approve API access.",
            T_PARTNER, DEV3,
            {"name": "Partner Service", "logical_unit": "partner-onboarding", "description": "Partner and credential management"},
            ["OAuth2", "mTLS"], ["partner", "onboarding", "credentials", "access"], "/partner/onboarding",
            [{"method": "POST", "path": "/v1/partners/register", "summary": "Register partner", "operation_id": "registerPartner"}, {"method": "GET", "path": "/v1/partners/{partnerId}/credentials", "summary": "List API credentials", "operation_id": "listCredentials"}],
            "PART", "822345678", "Partner Onboarding API", "partner/onboarding-svc", "openapi.yaml", "7c8d9e0f1a2b",
            ["Partner registration", "API keys", "Access approval"], ["Partner portal", "Admin"],
            pii=["partner_contact", "company_details"],
        ),
        api(
            "api-audit-activity", "Audit Log / Activity API", "customer",
            "Retrieve audit log and user activity for compliance and security.",
            T_CUSTOMER, DEV2,
            {"name": "Audit Service", "logical_unit": "customer-audit", "description": "Audit log and activity trail"},
            ["OAuth2", "mTLS"], ["audit", "compliance", "security", "activity"], "/customer/audit",
            [{"method": "GET", "path": "/v1/audit/logs", "summary": "Query audit logs", "operation_id": "getAuditLogs"}],
            "CUST", "922345678", "Audit API", "customer/audit-svc", "api/audit-spec.yaml", "8d9e0f1a2b3c",
            ["Compliance", "Security review", "Dispute"], ["Compliance", "Security", "Legal"],
            pii=["user_id", "ip_address", "action_details"],
        ),
        api(
            "api-speed-test", "Speed Test / Network Quality API", "network",
            "Trigger and retrieve speed test results and network quality metrics.",
            T_NETWORK, DEV3,
            {"name": "Network Quality Service", "logical_unit": "network-quality", "description": "Speed test and quality metrics"},
            ["OAuth2", "API_KEY"], ["network", "speed-test", "quality", "QoS"], "/network/speed-test",
            [{"method": "POST", "path": "/v1/speedtest/trigger", "summary": "Trigger speed test", "operation_id": "triggerSpeedTest"}, {"method": "GET", "path": "/v1/speedtest/{testId}/result", "summary": "Get speed test result", "operation_id": "getSpeedTestResult"}],
            "NET", "032345678", "Speed Test API", "network/speedtest-svc", "openapi/speedtest.yaml", "9e0f1a2b3c4d",
            ["Network diagnostics", "Customer support", "QoS monitoring"], ["Self-care", "Care", "NOC"],
            pii=["msisdn", "location"],
        ),
    ]

    out = {
        "_meta": {
            "schema_version": "1.0",
            "description": "API knowledge store – one object per API with end-to-end metadata for application consumption",
            "last_updated": str(date.today()),
            "total_apis": len(apis),
        },
        "apis": apis,
    }
    path = __file__.replace("build_knowledge_store.py", "api-knowledge-store.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print(f"Wrote {len(apis)} APIs to {path}")

if __name__ == "__main__":
    main()
